### ISSUE TITLE
App crash at startup

### ISSUE THREAD

**Issue by venkatn41** [handstandsam/ShoppingApp#32]
seeing this crash :

 ```
 java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/protocol/HttpRequestExecutor;
        at org.apache.http.impl.client.HttpClientBuilder.build(HttpClientBuilder.java:695)
        at com.github.tomakehurst.wiremock.http.HttpClientFactory.createClient(HttpClientFactory.java:76)
        at com.github.tomakehurst.wiremock.http.ProxyResponseRenderer.<init>(ProxyResponseRenderer.java:58)
        at com.github.tomakehurst.wiremock.core.WireMockApp.buildStubRequestHandler(WireMockApp.java:131)
        at com.github.tomakehurst.wiremock.WireMockServer.<init>(WireMockServer.java:73)
        at com.handstandsam.shoppingapp.mockaccount.Stubberator.<init>(Stubberator.kt:26)
        at com.handstandsam.shoppingapp.network.MockNetworkManager.init(MockNetworkManager.kt:20)
        at com.handstandsam.shoppingapp.network.MockNetworkManager.<init>(MockNetworkManager.kt:40)
        at com.handstandsam.shoppingapp.ServerDimensionKt.serverDimensionNetworkGraph(ServerDimension.kt:18)
        at com.handstandsam.shoppingapp.MyApplication$appGraph$2.invoke(MyApplication.kt:13)
        at com.handstandsam.shoppingapp.MyApplication$appGraph$2.invoke(Unknown Source:0)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.handstandsam.shoppingapp.MyApplication.getAppGraph(MyApplication.kt:10)
        at com.handstandsam.shoppingapp.MyApplication.onCreate(MyApplication.kt:19)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
```

**Comment by alexanderconner** [comment]
I am also seeing the same thing. After updating dependencies to run on the latest version Android Studio (build tools to gradle:4.2.0-beta02) and selecting the build variant to use the mockserverDebug, this is the error I see. I also see others having this issue in the comments for recent WireMock posts, such as here: https://medium.com/mindorks/efficient-android-testing-using-wiremock-and-espresso-cf2d7b7c735f.

**Comment by handstandsam** [comment]
Thanks, you can use the `inmemory` flavor instead and it should work.  I'll probably replace the wiremock flavor.  Sorry!

**Comment by handstandsam** [comment]
I just removed WireMock from the app and am now using MockWebServer https://github.com/handstandsam/ShoppingApp/pull/33

**Comment by alexanderconner** [comment]
Sam! Love the tool. MockWebServer would be the solution if we didn't use a 3rd party client. Until we can completely use regular okhttp/retrofit clients WireMock works great.
